### ISSUE TITLE
Compatibility issue with the latest version of dependencies

### ISSUE THREAD

**Issue by Qiuyi-Hong** [andrewlyden/PyPSA-GB#28]
Hello, 

I found the package brilliant, and I'd like to run some of the jupyter notebooks, e.g., `Unit Commitment.ipynb`. However, when I downloaded either the latest or the v1.0.0 version of the repository, I encountered some errors when running the `Unit Commitment.ipynb` with the `PyPSA-GB` virtual environment I downloaded based on the `PyPSA-GB_requirements.yml`. I self-diagnosed some of the issues and found the solutions, such as the incompatibility of `numpy 2.0`. However, I still couldn't run the entire notebook. 

Could you please let me know the specific version of each dependency so I can download them and run the notebook successfully?

Thank you for your help, and I look forward to hearing from you. 

Best regards,
Qiuyi

**Comment by sunedin** [comment]
Hi Qiuyi,

I've fixed the following package to specific version:

numpy==1.26.0
pandas==2.1.4
pypsa==0.25.1

It should run okay.

**Comment by Qiuyi-Hong** [comment]
Hello Wei,

Thanks for the prompt reply. I tried the specific version of the dependencies you provided. However, the issue remains. The problem is the 4th cell in `Unit Commitment.ipynb`. I got the `KeyError: '2050-01-01'` and `KeyError: 2050`. I downloaded both PyPSA-GB v1.0.0 and the latest version on GitHub. The issue remains the same for both versions. Could you please generate a new `PyPSA-GB_requirements.yml` so I can create a conda env to run the notebook? In addition, I would much appreciate your thoughts about the issue.

Best regards,
Qiuyi

**Comment by sunedin** [comment]
Can't get it to work without error neither; will need to find some time to fix it.

**Comment by Qiuyi-Hong** [comment]
Thank you, Wei. Please let me know when you fix the issue. I'm keen to run the notebook and show it to my colleagues.

**Comment by Qiuyi-Hong** [comment]
Hello Wei,

Thank you so much for the update. I much appreciate it. However, the issue still remains after trying to downgrade Pyomo to 6.5.0 along with other libraries. I have attempted both PyPSA-GB v1.0.0 and the latest version. If you have successfully run the `Unit Commitment.ipynb` without an error, could you please generate a new `PyPSA-GB_requirements.yml` so I can create the same virtual environment as yours? I would also love to know if you have any other solutions. 

Best regards,
Qiuyi
